export const LOAD_DEPENDENTS = 'LOAD_DEPENDENTS';
export const CREATE_DEPENDENT_SUCCESS = 'CREATE_DEPENDENT_SUCCESS';
export const CREATE_DEPENDENT_ERROR = 'CREATE_DEPENDENT_ERROR';
export const UPDATE_DEPENDENT_SUCCESS = 'UPDATE_DEPENDENT_SUCCESS';
export const UPDATE_DEPENDENT_ERROR = 'UPDATE_DEPENDENT_ERROR';
export const DESTROY_DEPENDENT = 'DESTROY_DEPENDENT';
