export const LOAD_USERPREPS = 'LOAD_USERPREPS';
export const TOGGLE_USERPREP_COMPLETED = 'TOGGLE_USERPREP_COMPLETED';
export const UPDATE_USERPREP_SUCCESS = 'UPDATE_USERPREP_SUCCESS';
export const UPDATE_USERPREP_ERROR = 'UPDATE_USERPREP_ERROR';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
