export const LOAD_ZONES = 'LOAD_ZONES';
export const CREATE_ZONE_SUCCESS = 'CREATE_ZONE_SUCCESS';
export const CREATE_ZONE_ERROR = 'CREATE_ZONE_ERROR';
export const UPDATE_ZONE_SUCCESS = 'UPDATE_ZONE_SUCCESS';
export const UPDATE_ZONE_ERROR = 'UPDATE_ZONE_ERROR';
export const DESTROY_ZONE = 'DESTROY_ZONE';
